global:
  scrape_interval: 15s

scrape_configs:
  - job_name: bugtracker
    static_configs:
      - targets:
          # Use localhost when scraping a locally running app. Replace with ACI FQDN:port when scraping the deployed instance.
          - localhost:8000
        labels:
          service: bugtracker
